apiVersion: v1
kind: Service
metadata:
  name: {{ template "kube-monitoring-telegram-bot.fullname" . }}
  labels:
    app: {{ template "kube-monitoring-telegram-bot.name" . }}
    chart: {{ template "kube-monitoring-telegram-bot.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "kube-monitoring-telegram-bot.name" . }}
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.externalPort }}
      targetPort: http
      name: kube-monitoring-telegram-bot