replicaCount: 1

image:
  repository: vientoprojects/kubernetes-monitoring-telegram-bot
  pullPolicy: IfNotPresent
  tag: latest

telegramBot:
  globalBotToken:
    use: false
    existingPasswordSecret: ~
    existingPasswordSecretKey: "global-bot-token"
    token: ""
  kubewatchBotToken:
    use: false
    existingPasswordSecret: ~
    existingPasswordSecretKey: "kubewatch-bot-token"
    token: ""
  prometheusBotToken:
    use: false
    existingPasswordSecret: ~
    existingPasswordSecretKey: "prometheus-bot-token"
    token: ""
  loggingLevel: info

pod:
  labels: {}
  annotations: {}
  nodeSelector: {}

service:
  type: ClusterIP
  internalPort: 8080
  externalPort: 8080